### ISSUE TITLE
Consider adding JSHint as a task

### ISSUE THREAD

**Issue by moloko** [cgkineo/adapt-buildkit-grunt#15]
https://github.com/gruntjs/grunt-contrib-jshint
together with https://github.com/sindresorhus/jshint-stylish

**Comment by taylortom** [comment]
This is in (See commit https://github.com/cgkineo/adapt-grunt/commit/84be1e65b4fd331cf2b56fb8616e62eb97c615cc), but I've turned most of the warnings off as they proved a bit too extensive...
